---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: win2012r2packer
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[win-base::default]
    attributes:
